POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
    "type": "driver",
    "email": "zonetwyn@gmail.com",
    "password": "awesome",
    "name": "Wilfried Noel",
    "phone": "+987654321",
    "pictureUrl": "http://res.cloudinary.com/booking-19/image/upload/v1551741661/users/b5tmxgjkzqylp5qhk2xp.jpg"
}