GET http://localhost:5000/api/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1YzdkYjMyZmUwNDc2NDI0NDRkZjU2NDUiLCJlbWFpbCI6ImF3ZXNvbWVAYXdlc29tZS5jb20iLCJpYXQiOjE1NTE3NDE4ODIsImV4cCI6MTU1MTgyODI4Mn0.vbxFbJYAqVBQleZiyeupMM7V0tForFYQiaZrhFgv78M